export const PROJECT_FORM = "PROJECT_FORM";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const PROJECT_FORM_VALIDATION = "PROJECT_FORM_VALIDATION";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECT_ERROR = "PROJECT_ERROR";

export const GET_TASKS = "GET_TASKS";
export const ADD_TASK = "ADD_TASK";
export const TASK_FORM_VALIDATION = "TASK_FORM_VALIDATION";
export const DELETE_TASK = "DELETE_TASK";
export const CURRENT_TASK = "CURRENT_TASK";
export const EDIT_TASK = "EDIT_TASK";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SUCCESSFULL_REGISTRATION = "SUCCESSFULL_REGISTRATION";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const GET_USER = "GET_USER";
export const SUCCESSFULL_LOGIN = "SUCCESSFULL_LOGIN";
export const LOGING_ERROR = "LOGING_ERROR";
export const LOG_OUT = "LOG_OUT";
